title: Radhika Mittal # your name (or website title) here
logo: "/images/radhika.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An aspiring computer architect, my research interests are hardware acceleration, computer systems and UAV systems.
  <br><br>
  I am currently a research assistant at the Indian Institute of Science, Bangalore, India with Prof. Yogesh Simmhan at DREAM:Lab.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/rad-mit/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/rad-mit/">View my CV</a> 
<br><br>
  <br><br>
remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme
google_analytics: G-TSLPJFY8B4 # your Google Analytics tracking ID here
