title: Radhika Mittal # your name (or website title) here
logo: "/images/radhika.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An aspiring computer architect, a bit in love with robots ...
  <br><br>
  # Second description 
  # <br><br>
  <a href="https://www.linkedin.com/in/rad-mit/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-TSLPJFY8B4 # your Google Analytics tracking ID here
